### PR TITLE
Pass undefined instead of null from connect

### PR DESCRIPTION
**Pull request by einarlove**
Firebase can't store `null` meaning `null` is equivalent to `undefined`. This also allows you to define defaultProps or pass from parent.

### CODE REVIEW

**Comment by simenbrekken** [comment]
Could you add a test case seeing this will introduce a breaking change?

**Comment by einarlove** [comment]
Can you give me an example?

**Comment by simenbrekken** [comment]
There's also an optimization possibility at https://github.com/unfold/react-firebase/blob/f9df0fe27ba7298e7016b8eb203964d195ce8bc9/src/connect.js#L92-L99 where we could avoid a `setState` by checking that key already exists in our `subscriptionState`:

```js

**Comment by simenbrekken** [comment]
Superceded by #19

**Pull request closed without merging**
