### PR TITLE
Properly unsubscribe listeners

### PR DESCRIPTION
**Pull request by akofman**
It looks like `omitBy` didn't do the job as expected so I've just updated the way the listeners were removed. 
Also it's not possible to test async operations with `tape` so I can't check the state updates from the tests. Maybe `blue-tape` could be a solution if needed, just a suggestion ;)

Hope it's ok !

### CODE REVIEW

**Comment by simenbrekken** [comment]
@akofman Thanks for the PR! I'll look into it as soon as possible.

What do you mean by "testing state updates"? That you can't test the state of a subscription inside a test?

**Comment by akofman** [comment]
Indeed, I revert the changes. Concerning the state updates, I meant it's difficult with `tape` to test async/Promise parts so you can't easily update the state then check it. So yes - I can't check the state of the subscriptions.

**Comment by simenbrekken** [comment]
@akofman Since we're mocking Firebase there's no need to do anything async, you can just [grab the state like we're currently doing in the tests](https://github.com/unfold/react-firebase/blob/master/src/tests/connect-test.js#L75)

If you'd want to test something async with tape you can simply move the `assert.end` invocation:

```js
test('Should test my promise', assert => {
  myPromiseFunction()
    .then(result => {
      assert.equal(result, true)
      assert.end()
    })
  })
})
```

This is actually [how `blue-tape` implements this already](https://github.com/spion/blue-tape/blob/master/blue-tape.js#L16-L21)

**Comment by akofman** [comment]
Aaaaaah good to know thanks à lot !

**Comment by simenbrekken** [comment]
Seems CircleCI is having a bad day. I've manually run the tests locally and they pass.

**Pull request merged**
