### PR TITLE
Import less from Firebase

### PR DESCRIPTION
**Pull request by einarlove**
Running through webpack after minification and tree shaking excluding react, bundle size was reduced from 319 kB to 166 kB. Over 50% in size reduction. 👍 

From
screen shot 2017-01-10 at 18 47 12
To
screen shot 2017-01-10 at 18 46 56

### CODE REVIEW

**Comment by einarlove** [comment]
Closes #14

**Comment by akofman** [comment]
Hello @einarlove , what tool did you use to visualize the bundle size ? It looks really convenient :)

**Comment by einarlove** [comment]
[source-map-explorer](https://www.npmjs.com/package/source-map-explorer) ✨

**Comment by akofman** [comment]
:+1: Thanks !

**Pull request merged**
