### PR TITLE
Pass along errors from firebase

### LINKED ISSUE #43: Handle errors?
There is currently no way of capturing errors from database reads, for example if permission is denied. We could add a handler to https://github.com/unfold/react-firebase/blob/master/src/connect.js#L106

```js
subscriptionRef.on('value', update, onError)
```

But how to map that value to props? We could just map the value to the same prop key, which would require an additional check `props[key] instanceof Error`, or we could extend the `mergeProps ` function to also pass and `error` argument that the user could map to props as they desire, something like (we could attach the key to the error for convenience):

```js
const mergeProps = (ownProps, firebaseProps, error) => ({
  error: 'There was an error reading ' + error.key + ' Firebase said: ' + error.message
})
```

### PR DESCRIPTION
**Pull request by einarlove**
Capture errors from firebase and pass them along to connected component.

Example:
```js
const App = ({ data }) => {
  if (data instanceof Error) return (
    <div>Oh no! {data.message}</div>
  )
  
  return (
    <div>
      {JSON.stringify(data)}
    </div>
  )
}

connect({
  data: 'path-to-data',
})(App)
```

Resolves #43

### CODE REVIEW

**Comment by einarlove** [comment]
I'm not sure how to handle error handling of large amount of refs.
```js
const App = props => {
  
  if (
    props.one instanceof Error 
    props.two instanceof Error ||
    props.three instanceof Error ||
    props.four instanceof Error ||
    props.five instanceof Error ||
  ) {
    return <div>🚫</div>
  }

  return <div>✅</div>
}

connect({
  one: 'one',
  two: 'two',
  three: 'three',
  four: 'four',
  five: 'five',
})(app)
```

**Comment by simenbrekken** [comment]
@einarlove It's IMHO more flexible being able to define what should be passed to the component, either the first error (fatal), or every error in as an array or as an object with a field mapping.

**Comment by einarlove** [comment]
So, you're for https://github.com/unfold/react-firebase/pull/44 instead since it deals with errors in `mapSubscriptionsToProps`?

**Comment by simenbrekken** [comment]
@einarlove This might be a bit less user-friendly but it's a lot more flexible being able to handle this in user-land. E.g. Return null on error if a field isn't critical. So no, I like this approach more

**Comment by einarlove** [comment]
If we merge this, what semver release should this be? No change in API, but the behaviour has changed if you get an error. Today it's just silent and the prop is null, if this is merged, you'll get a React error if you try to render the Error.

**Comment by simenbrekken** [comment]
@einarlove While I'm not completely sure, I think breaking the most central contract of the existing API warrants a major bump.

**Comment by einarlove** [comment]
Maybe we could add option to catch all errors like:
```js
const onFirebaseError = error => {
  error.code // PERMISSION_DENIED
  error.message // permission_denied at /forbidden: Client doesn't have permission to access the desired data.

  if (error.code === 'NETWORK_ERROR') {
    showNoInternetMessage()
  }
  if (error.code === 'PERMISSION_DENIED') {
    logoutUser()
  }
}

<Provider firebaseApp={firebaseApp} onError={onFirebaseError}>
 <App />
</Provider>
```
and silence the errors below with:
```js
const onError = error => {
  if (!this.mounted) return

  if (this.context.firebaseAppErrorHandler) {
    this.context.firebaseAppErrorHandler(error)
    return
  }
  …
```

**Comment by simenbrekken** [comment]
Continued in https://github.com/unfold/react-firebase/tree/merge-props-error-handling

**Pull request closed without merging**
